@Attribution
@Web-bat-tier-1

Feature: Elaine amendment abandonment

  Scenario Outline: Registered User makes a regular reservation after abandonment

    Given I start with a new browser
    And I set test domain to "<domain>"
    And I clear cookies
    And I have registered regular user with random email
    When I go to restref page for rid "<preabandonrid>"
    Then I navigate to url "<Restref_URL>"
    And I set reservation date to "<days_fwd>" days from today
    And I set reservation time to "<time>"
    And I set party size to "<party_sz>"
    And I click "Find a Table"
    Then I click time slot "<time>" for restaurant "<rest_name>" on "<days_fwd>" days from today
    And I click on Sign in link and login as registered user
    And I fill in "Phone" with "<phone_number>"
    And I complete reservation
    ##If user fname and lname is nil, use the name that was generated by the system
    Then I should see user name "" ""and conf number on view page
    Then I should see POP "<points_msg>" points message
    Then I cancel reservation

  @Region-NA @Domain-COM
  Scenarios:
    | domain |Restref_URL                                                           |          rest_name        |  phone_number | days_fwd |  time   |    preabandonrid  | party_sz |                            points_msg                          |
    | .com   | http://www.opentable.com/restaurant/profile/(COM-GuestCenterRest-RID)|(COM-GuestCenterRest-Name) | 415-232-5555  |7         |6:30 PM  | (COM-Connect2-RID)|      2   | You will earn 100 points upon dining.Learn more about points. |
