class Domain
  attr_accessor :rest, :db_name, :charm_domain_selector, :charm_address, :db_server_address, :www_domain_selector, :RESERVATION, :primary_metro_id, :primary_country_id, :mobile, :webserver_sitetype_id, :webserver_site_port, :umami_domain_selector
  attr_accessor :quality_center_test_set, :locale, :charm_prod_address, :www_otrestaurant_selector, :db_otr_server_address, :db_otr_name, :region_id, :region_lat, :region_long, :soap_url, :domain, :yml_param, :availServer_sitetype_id, :availServer_site_port
  attr_accessor :prod_primary_metro_id, :prod_region_id, :language_id, :internal_services, :reservation_service, :reservation_service_port, :region, :logdb_server_address, :logdb_name, :int_services, :device_notification_service_url, :resource_locator_service_url
  attr_accessor :offeravailabilitydb_server_address, :offeravailabilitydb_name, :ios_bundle_id, :prod_int_services, :user_authentication_service_url, :db_user_name, :db_password, :f5controller_service_url, :domain_id, :metro_time_zone, :erb_domain_selector, :resource_locator_domain
  attr_accessor :umami_api_hosts, :umami_front_end_vars, :umami_pdiff_baseline_image_dir, :umami_pdiff_dir, :tms_prod_url
  attr_accessor :user_api_host, :restaurant_service, :restaurant_service_ci, :restaurant_service_prod, :restaurant_service_preprod, :availability_service, :availability_domain, :availability_service_ci, :availability_service_prod, :availability_service_preprod
  attr_accessor :user_api_host_PROD, :user_api_host_PP, :user_api_host_CI
  attr_accessor :reservation_service_host, :reservation_service_host_CI, :reservation_service_host_PP, :reservation_service_host_PROD
  attr_accessor :reso_serv_port , :reso_serv_port_PROD , :reso_serv_port_PP , :reso_serv_port_CI

  def initialize(domain)
    @device_notification_service_url = "devicenotification.services.opentable.com"
    @user_authentication_service_url = "userauthentication.services.opentable.com"
    @db_user_name = "automation"
    @db_password = "aut0m8er"
    @f5controller_service_url = "f5controller.services.opentable.com"
    @resource_locator_service_url = "resourcelocator.services.opentable.com"
   # domain = domain.downcase
    puts "domain is " + domain
    @umami_api_hosts = {}
    @umami_front_end_vars = {}
    @restaurant_service_ci = "restaurant-ci.otenv.com"
    @restaurant_service_preprod = "restaurant-pp.otenv.com"
    @restaurant_service = 'restaurant.otenv.com'


    case domain.to_s.downcase
      when ".com"
        @domain = 'COM'
        @primary_metro_id = "4"
        @primary_country_id = "US"
        @charm_domain_selector = "OpenTable.com"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.com"
        @charm_prod_address = "charm.opentable.com.ot"
        @db_server_address ="webdb-na-primary"
        @db_name = "webdb"
        @logdb_server_address ="weblogdb-na-primary"
        @logdb_name = "WebLogDB"
        @mobile = 'm.opentable.com'
        @user_api_host_CI = 'user-na-ci.otenv.com'
        @user_api_host_PP = 'user-na-pp.otenv.com'
        @user_api_host_PROD = 'user-na-sc.otenv.com'
        @reservation_service_host_CI ='reservation-na-ci.otenv.com'
        @reservation_service_host_PP ='reservation-na-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-na-sc.otenv.com'
        @reso_serv_port_PROD = "3045"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @rest = 'www.opentable.com'
        @availability_service = "availability-na.otenv.com"
        @availability_service_ci = "availability-na-ci-sf.otenv.com"
        @availability_service_preprod = "availability-na-pp-sf.otenv.com"
        @availability_service_prod = "availability-na-prod-sc.otenv.com"
        @availability_domain = 'com'
        $RESERVATION["restparam"] ="COM"
        $RESERVATION["isRestrefa"] = false
        @webserver_sitetype_id = '101'
        @webserver_site_port = '2020'
        @quality_center_test_set = 'COM'
        @locale = 'en-US'
        @www_otrestaurant_selector = "www.otrestaurant#{domain}"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id = "5"
        @region_lat ="37.7872920"
        @region_long = "-122.4128170"
        @soap_url ="http://www.opentable.com/webservices/V3.asmx"
        @yml_param = "COM"
        @availServer_sitetype_id = '809'
        @availServer_site_port = '3030'
        @prod_primary_metro_id = "1"
        @prod_region_id = "134"
        @internal_services = 'int-na-svc'
        @reservation_service = 'reservation.na.services.opentable.com'
        @region = 'NA'
        @language_id = '1'
        @int_services = "na.services.opentable.com"
        @ios_bundle_id = "com.contextoptional.OpenTable-beta"
        @prod_int_services = 'int-na-svc.otsql.opentable.com'
        @domain_id = '1'
        @metro_time_zone = 'America/Los_Angeles'
        @erb_domain_selector = 'erb.opentable.com'
        @resource_locator_domain = 'com'
        @umami_domain_selector = "https://guestcenter.opentable.com"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @points_txt = ""
        @ps_txt = ""
        @restaurant_service_prod = "restaurant-sc.otenv.com"

      when ".com/fr-ca"
        @domain = 'COM/FR-CA'
        @primary_metro_id = '74'
        @primary_country_id = "CA"
        @charm_domain_selector = "OpenTable.com"
        @charm_prod_address = "charm.opentable.com.ot"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.com"
        @db_server_address ="webdb-na-primary"
        @db_name = "webdb"
        @logdb_server_address ="weblogdb-na-primary"
        @logdb_name = "WebLogDB"
        @mobile = 'm.opentable.com'
        @rest = 'www.opentable.com'
        $RESERVATION["restparam"] ="FRCA"
        $RESERVATION["isRestref"] = true
        @webserver_sitetype_id = '111'
        @webserver_site_port = '2020'
        @quality_center_test_set = 'FR-CA'
        @locale = 'fr-CA'
        @www_otrestaurant_selector = "www.otrestaurant.com"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id = "164"
        @region_lat ="43.6608470"
        @region_long = "-79.4004220"
        @soap_url ="http://www.opentable.com/webservices/V3.asmx"
        @yml_param = "FRCA"
        @availServer_sitetype_id = '809'
        @availServer_site_port = '3030'
        @prod_primary_metro_id = "1"
        @prod_region_id = "134"
        @internal_services = 'int-na-svc'
        @region = 'NA'
        @language_id = '82'
        @int_services = "na.services.opentable.com"
        @ios_bundle_id = "com.contextoptional.OpenTable-beta"
        @prod_int_services = 'int-na-svc.otsql.opentable.com'
        @domain_id = '1'
        @reservation_service = 'reservation.na.services.opentable.com'
        @metro_time_zone = 'Canada/Eastern'
        @erb_domain_selector = 'erb.opentable.com'
        @resource_locator_domain = 'ca'
        @umami_domain_selector = "https://guestcenter.opentable.ca"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @availability_service = "availability-na.otenv.com"
        @availability_service_preprod = "availability-na-pp-sf.otenv.com"
        @availability_service_prod = "availability-na-prod-sc.otenv.com"
        @availability_service_ci = "availability-na-ci-sf.otenv.com"
        @availability_domain = 'com'
     #   @user_api_host = 'int-na-svc'
        @user_api_host_CI = 'int-na-svc'
        @user_api_host_PP = 'int-na-svc.qasql.opentable.com'
        @user_api_host_PROD = 'user-na-sc.otenv.com'
        @reservation_service_host_CI ='reservation-na-ci.otenv.com'
        @reservation_service_host_PP ='reservation-na-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-na-sc.otenv.com'
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @reso_serv_port_PROD = "3045"
        @restaurant_service_prod = "restaurant-sc.otenv.com"

      when ".com.mx"
        @domain = 'COM.MX'
        @primary_metro_id = '57'
        @primary_country_id = "MX"
        @charm_domain_selector ="OpenTable.com.mx"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.com"
        @charm_prod_address = "charm.opentable.com.ot"
        @db_server_address ="webdb-na-primary"
        @db_name = "webdb"
        @logdb_server_address ="weblogdb-na-primary"
        @logdb_name = "WebLogDB"
        @mobile = 'm.opentable.com'
        @rest = 'www.opentable.com.mx'
        #   @user_api_host = 'int-na-svc'
        @user_api_host_CI = 'int-na-svc'
        @user_api_host_PP = 'int-na-svc.qasql.opentable.com'
        @user_api_host_PROD = 'user-na-sc.otenv.com'
        @reservation_service_host_CI ='reservation-na-ci.otenv.com'
        @reservation_service_host_PP ='reservation-na-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-na-sc.otenv.com'
        @reso_serv_port_PROD = "3045"
        @availability_service = "availability-na.otenv.com"
        @availability_service_preprod = "availability-na-pp-sf.otenv.com"
        @availability_service_prod = "availability-na-prod-sc.otenv.com"
        @availability_service_ci = "availability-na-ci-sf.otenv.com"
        @availability_domain = 'commx'
        $RESERVATION["restparam"] ="MX"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id = '112'
        @webserver_site_port = '2035'
        @quality_center_test_set = 'MX'
        @locale = 'es-MX'
        @www_otrestaurant_selector = "www.otrestaurant#{domain}"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="110"
        @region_lat ="19.4184660"
        @region_long = "-99.1780120"
        @soap_url ="http://www.opentable.com.mx/webservices/V3.asmx"
        @yml_param = "MX"
        @availServer_sitetype_id = '809'
        @availServer_site_port = '3030'
        @prod_primary_metro_id = "1"
        @prod_region_id = "181"
        @internal_services = 'int-na-svc'
        @language_id = '6'
        @int_services = "na.services.opentable.com"
        @prod_int_services = 'int-na-svc.otsql.opentable.com'
        @domain_id = '6'
        @region = 'NA'
        @metro_time_zone = 'Mexico/General'
        @erb_domain_selector = 'erb.opentable.com'
        @reservation_service = 'reservation.na.services.opentable.com'
        @resource_locator_domain = 'mx'
        @ios_bundle_id = "com.contextoptional.OpenTable-beta"
        @umami_domain_selector = "https://guestcenter.opentable.mx"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".com.mx/en-us"
        @domain = 'COM.MX/en-US'
        @primary_metro_id = '57'
        @primary_country_id = "MX"
        @charm_domain_selector ="OpenTable.com.mx"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.com"
        @charm_prod_address = "charm.opentable.com.ot"
        @db_server_address ="webdb-na-primary"
        @db_name = "webdb"
        @logdb_server_address ="weblogdb-na-primary"
        @logdb_name = "WebLogDB"
        @mobile = 'm.opentable.com'
        @rest = 'www.opentable.com.mx'
        #   @user_api_host = 'int-na-svc'
        @user_api_host_CI = 'int-na-svc'
        @user_api_host_PP = 'int-na-svc.qasql.opentable.com'
        @user_api_host_PROD = 'user-na-sc.otenv.com'
        @reservation_service_host_CI ='reservation-na-ci.otenv.com'
        @reservation_service_host_PP ='reservation-na-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-na-sc.otenv.com'
        @reso_serv_port_PROD = "3045"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        $RESERVATION["restparam"] ="MX"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id ='113'
        @webserver_site_port = '2035'
        @quality_center_test_set = 'MX.en-US'
        @locale = 'es-MX'
        @www_otrestaurant_selector = "www.otrestaurant.com"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="110"
        @region_lat ="19.4184660"
        @region_long = "-99.1780120"
        @soap_url ="http://www.opentable.com/webservices/V3.asmx"
        @yml_param = "MX"
        @soap_url ="http://www.opentable.com.mx/webservices/V3.asmx"
        @availServer_sitetype_id = '809'
        @availServer_site_port = '3030'
        @prod_primary_metro_id = "1"
        @prod_region_id = "181"
        @internal_services = 'int-na-svc'
        @language_id = '1'
        @int_services = "na.services.opentable.com"
        @prod_int_services = 'int-na-svc.otsql.opentable.com'
        @domain_id = '6'
        @region = 'NA'
        @metro_time_zone = 'Mexico/General'
        @erb_domain_selector = 'erb.opentable.com'
        @reservation_service = 'reservation.na.services.opentable.com'
        @resource_locator_domain = 'mx'
        @umami_domain_selector = "https://guestcenter.opentable.mx"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @availability_service = "availability-na.otenv.com"
        @availability_service_preprod = "availability-na-pp-sf.otenv.com"
        @availability_service_prod = "availability-na-prod-sc.otenv.com"
        @availability_service_ci = "availability-na-ci-sf.otenv.com"
        @availability_domain = 'commx'
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".jp"
        @domain = 'JP'
        @primary_metro_id = '201'
        @primary_country_id = "JP"
        @charm_domain_selector="OpenTable.jp"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.jp"
        @charm_prod_address = "charm-asia.opentable.com.ot"
        @db_server_address ="webdb-asia-primary"
        @db_name = "webdb_asia"
        @logdb_server_address ="weblogdb-asia-primary"
        @logdb_name = "WebLogDB_Asia"
        @mobile = 'm.opentable.jp'
        @rest = 'www.opentable.jp'
        @user_api_host_CI = 'int-ap-svc'
        @user_api_host_PP = 'int-ap-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-ap-svc.otsql.opentable.com'
        @reservation_service_host_CI ='reservation-ap-ci.otenv.com'
        @reservation_service_host_PP ='reservation-ap-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-ap-sc.otenv.com'
        @reso_serv_port_PROD = "3047"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_service = "availability-ap.otenv.com"
        @availability_service_ci = "availability-ap-ci-sf.otenv.com"
        @availability_service_preprod = "availability-ap-pp-sf.otenv.com"
        @availability_service_prod = "availability-ap-prod-sc.otenv.com"
        @availability_domain = 'jp'
        $RESERVATION["restparam"] ="JP"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id ='102'
        @webserver_site_port = '2060'
        @quality_center_test_set = 'JP'
        @locale = 'ja-JP'
        @www_otrestaurant_selector = "www.otrestaurant#{domain}"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1001"
        @region_lat ="35.6670860"
        @region_long = "139.7304560"
        @soap_url ="http://www.opentable.jp/webservices/V3.asmx"
        @yml_param = "JP"
        @availServer_sitetype_id = '811'
        @availServer_site_port = '3032'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1007"
        @internal_services = 'int-ap-svc'
        @reservation_service = 'reservation.ap.services.opentable.com'
        @region = 'AP'
        @language_id = '2'
        @int_services = "ap.services.opentable.com"
        @prod_int_services = 'int-ap-svc.otsql.opentable.com'
        @domain_id = '2'
        @metro_time_zone = 'Asia/Tokyo'
        @erb_domain_selector = 'erb.opentable.jp'
        @resource_locator_domain = 'jp'
        @umami_domain_selector = "https://guestcenter.opentable.jp"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".jp/en-gb"
        @domain = 'JP/EN-GB'
        @primary_metro_id = '201'
        @primary_country_id = "JP"
        @charm_domain_selector="OpenTable.jp"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.jp"
        @charm_prod_address = "charm-asia.opentable.com.ot"
        @db_server_address ="webdb-asia-primary"
        @db_name = "webdb_asia"
        @logdb_server_address ="weblogdb-asia-primary"
        @logdb_name = "WebLogDB_Asia"
        @mobile = 'm.opentable.com'
        @user_api_host_CI  = 'int-ap-svc'
        @user_api_host_PP = 'int-ap-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-ap-svc.otsql.opentable.com'
        @reservation_service_host_CI ='reservation-ap-ci.otenv.com'
        @reservation_service_host_PP ='reservation-ap-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-ap-sc.otenv.com'
        @reso_serv_port_PROD = "3047"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_service = "availability-ap.otenv.com"
        @availability_service_preprod = "availability-ap-pp-sf.otenv.com"
        @availability_service_prod = "availability-ap-prod-sc.otenv.com"
        @availability_service_ci = "availability-ap-ci-sf.otenv.com"
        @availability_domain = 'jp'
        @rest = 'www.opentable.jp'
        $RESERVATION["restparam"] ="JP"
        $RESERVATION["isRestref"] = true
        @webserver_sitetype_id ='108'
        @webserver_site_port = '2060'
        @quality_center_test_set = 'JP.en-GB'
        @locale = 'ja-JP'
        @www_otrestaurant_selector = "www.otrestaurant.jp"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1001"
        @region_lat ="35.6670860"
        @region_long = "139.7304560"
        @soap_url ="http://www.opentable.jp/webservices/V3.asmx"
        @yml_param = "JP"
        @availServer_sitetype_id = '811'
        @availServer_site_port = '3032'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1007"
        @internal_services = 'int-ap-svc'
        @language_id = '70'
        @int_services = "ap.services.opentable.com"
        @prod_int_services = 'int-ap-svc.otsql.opentable.com'
        @domain_id = '2'
        @region = 'AP'
        @metro_time_zone = 'Asia/Tokyo'
        @erb_domain_selector = 'erb.opentable.jp'
        @reservation_service = 'reservation.ap.services.opentable.com'
        @resource_locator_domain = 'jp'
        @umami_domain_selector = "https://guestcenter.opentable.jp"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".jp/en-us"
        @domain = 'JP/EN-US'
        @primary_metro_id = '201'
        @primary_country_id = "JP"
        @charm_domain_selector="OpenTable.jp"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.jp"
        @charm_prod_address = "charm-asia.opentable.com.ot"
        @db_server_address ="webdb-asia-primary"
        @db_name = "webdb_asia"
        @logdb_server_address ="weblogdb-asia-primary"
        @logdb_name = "WebLogDB_Asia"
        @mobile = 'm.opentable.com'
        @user_api_host_CI  = 'int-ap-svc'
        @user_api_host_PP = 'int-ap-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-ap-svc.otsql.opentable.com'
        @availability_service = "availability-ap.otenv.com"
        @availability_service_preprod = "availability-ap-pp-sf.otenv.com"
        @availability_service_prod = "availability-ap-prod-sc.otenv.com"
        @availability_service_ci = "availability-ap-ci-sf.otenv.com"
        @reservation_service_host_CI ='reservation-ap-ci.otenv.com'
        @reservation_service_host_PP ='reservation-ap-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-ap-sc.otenv.com'
        @reso_serv_port_PROD = "3047"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
       # @user_api_host = 'int-ap-svc'
        @availability_domain = 'jp'
        @rest = 'www.opentable.jp'
        $RESERVATION["restparam"] ="JP"
        $RESERVATION["isRestref"] = true
        @webserver_sitetype_id ='108'
        @webserver_site_port = '2060'
        @quality_center_test_set = 'JP.en-GB'
        @locale = 'ja-JP'
        @www_otrestaurant_selector = "www.otrestaurant.jp"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1001"
        @region_lat ="35.6670860"
        @region_long = "139.7304560"
        @soap_url ="http://www.opentable.jp/webservices/V3.asmx"
        @yml_param = "JP"
        @availServer_sitetype_id = '811'
        @availServer_site_port = '3032'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1007"
        @internal_services = 'int-ap-svc'
        @language_id = '70'
        @int_services = "ap.services.opentable.com"
        @prod_int_services = 'int-ap-svc.otsql.opentable.com'
        @domain_id = '2'
        @region = 'AP'
        @metro_time_zone = 'Asia/Tokyo'
        @erb_domain_selector = 'erb.opentable.jp'
        @reservation_service = 'reservation.ap.services.opentable.com'
        @resource_locator_domain = 'jp'
        @umami_domain_selector = "https://guestcenter.opentable.jp"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".fr", ".fr/en-gb"
        @domain = 'FR'
        @primary_metro_id = '224'
        @primary_country_id = "FR"
        @charm_domain_selector="OpenTable.fr"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.eu"
        @charm_prod_address = "charm-eu.opentable.com.ot"
        @db_server_address ="webdb-eu-primary"
        @db_name = "webdb_eu"
        @logdb_server_address ="weblogdb-eu-primary"
        @logdb_name = "WebLogDB_EU"
        @mobile = 'm.opentable.com'
        @webserver_sitetype_id ='104'
        @locale = 'fr-FR'
        @www_otrestaurant_selector = "www.otrestaurant.de"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1059"
        @region_lat ="48.8660020"
        @region_long = "2.3148880"
        @soap_url ="http://www.opentable.fr/webservices/V3.asmx"
        @yml_param = "FR"
        @availServer_sitetype_id = '810'
        @availServer_site_port = '3031'
        @internal_services = 'int-eu-svc'
        @language_id = '4'
        @int_services = "eu.services.opentable.com"
        @prod_int_services = 'int-eu-svc.otsql.opentable.com'
        @domain_id = '4'
        @region = 'EU'
        @metro_time_zone = 'Europe/Paris'
        @erb_domain_selector = 'erb.opentable.fr'
        @umami_domain_selector = "https://guestcenter.opentable.ca"
        @tms_prod_url = "transaction-messaging.eu.services.opentable.com"
        @availability_service = "availability-na.otenv.com"
        @availability_service_preprod = "availability-na-pp-sf.otenv.com"
        @availability_service_prod = "availability-na-prod-sc.otenv.com"
        @availability_service_ci = "availability-na-ci-sf.otenv.com"
        @availability_domain = 'com'
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".de"
        @domain = 'DE'
        @primary_metro_id = '227'
        @primary_country_id = "DE"
        @charm_domain_selector="OpenTable.de"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.eu"
        @charm_prod_address = "charm-eu.opentable.com.ot"
        @db_server_address ="webdb-eu-primary"
        @db_name = "webdb_eu"
        @logdb_server_address ="weblogdb-eu-primary"
        @logdb_name = "WebLogDB_EU"
        @mobile = 'm.opentable.de'
        @rest = 'www.opentable.de'
        @user_api_host_CI  = 'int-eu-svc'
        @user_api_host_PP = 'int-eu-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-eu-svc.otsql.opentable.com'
        @availability_service = "availability-eu.otenv.com"
        @reservation_service_host_CI ='reservation-eu-ci.otenv.com'
        @reservation_service_host_PP ='reservation-eu-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-eu-ln.otenv.com'
        @reso_serv_port_PROD = "3046"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_service_preprod = "availability-eu-pp-sf.otenv.com"
        @availability_service_prod = "availability-eu-prod-ln.otenv.com"
        @availability_service_ci = "availability-eu-ci-sf.otenv.com"
        @availability_domain = 'de'
        $RESERVATION["restparam"] ="DE"
        @webserver_sitetype_id ='103'
        @webserver_site_port = '2022'
        @quality_center_test_set = 'DE'
        @locale = 'de-DE'
        @www_otrestaurant_selector = "www.otrestaurant#{domain}"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1038"
        @region_lat ="52.5071700"
        @region_long = "13.3728390"
        @soap_url ="http://www.opentable.de/webservices/V3.asmx"
        @yml_param = "DE"
        @availServer_sitetype_id = '810'
        @availServer_site_port = '3031'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1002"
        @internal_services = 'int-eu-svc'
        @language_id = '3'
        @int_services = "eu.services.opentable.com"
        @prod_int_services = 'int-eu-svc.otsql.opentable.com'
        @domain_id = '3'
        @region = 'EU'
        @metro_time_zone = 'Europe/Paris'
        @erb_domain_selector = 'erb.opentable.de'
        @reservation_service = 'reservation.eu.services.opentable.com'
        @resource_locator_domain = 'de'
        @umami_domain_selector = "https://guestcenter.opentable.de"
        @tms_prod_url = "transaction-messaging.eu.services.opentable.com"
        @restaurant_service_prod  = "restaurant-ln.otenv.com"

      when ".de/en-gb"
        @domain = 'DE/EN-GB'
        @primary_metro_id = '227'
        @primary_country_id = "DE"
        @charm_domain_selector="OpenTable.de"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.eu"
        @charm_prod_address = "charm-eu.opentable.com.ot"
        @db_server_address ="webdb-eu-primary"
        @db_name = "webdb_eu"
        @logdb_server_address ="weblogdb-eu-primary"
        @logdb_name = "WebLogDB_EU"
        @mobile = 'm.opentable.de'
        @rest = 'www.opentable.de'
        $RESERVATION["restparam"] ="DE"
        $RESERVATION["isRestref"] = true
        @webserver_sitetype_id = '109'
        @webserver_site_port = '2022'
        @quality_center_test_set = 'DE.en-GB'
        @locale = 'de-DE'
        @www_otrestaurant_selector = "www.otrestaurant.de"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1038"
        @region_lat ="52.5071700"
        @region_long = "13.3728390"
        @soap_url ="http://www.opentable.de/webservices/V3.asmx"
        @yml_param = "DE"
        @availServer_sitetype_id = '810'
        @availServer_site_port = '3031'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1002"
        @internal_services = 'int-eu-svc'
        @language_id = '70'
        @int_services = "eu.services.opentable.com"
        @prod_int_services = 'int-eu-svc.otsql.opentable.com'
        @domain_id = '3'
        @region = 'EU'
        @metro_time_zone = 'Europe/Paris'
        @erb_domain_selector = 'erb.opentable.de'
        @reservation_service = 'reservation.eu.services.opentable.com'
        @resource_locator_domain = 'de'
        @umami_domain_selector = "https://guestcenter.opentable.de"
        @tms_prod_url = "transaction-messaging.eu.services.opentable.com"
        @availability_service = "availability-eu.otenv.com"
        @availability_service_preprod = "availability-eu-pp-sf.otenv.com"
        @availability_service_prod = "availability-eu-prod-ln.otenv.com"
        @availability_service_ci = "availability-eu-ci-sf.otenv.com"
        @availability_domain = 'de'
        @user_api_host_CI  = 'int-eu-svc'
        @user_api_host_PP = 'int-eu-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-eu-svc.otsql.opentable.com'
        @reservation_service_host_CI ='reservation-eu-ci.otenv.com'
        @reservation_service_host_PP ='reservation-eu-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-eu-ln.otenv.com'
        @reso_serv_port_PROD = "3046"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @restaurant_service_prod  = "restaurant-ln.otenv.com"

      when ".co.uk"
        @domain = 'CO.UK'
        @primary_metro_id = '72'
        @primary_country_id = "UK"
        @charm_domain_selector="OpenTable.co.uk"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.eu"
        @charm_prod_address = "charm-eu.opentable.com.ot"
        @db_server_address ="webdb-eu-primary"
        @db_name = "webdb_eu"
        @logdb_server_address ="weblogdb-eu-primary"
        @logdb_name = "WebLogDB_EU"
        @offeravailabilitydb_server_address ="otofferavailability-eu-primary"
        @offeravailabilitydb_name = "OTOfferAvailability_EU"
        @mobile = 'm.opentable.co.uk'
        @rest = 'www.opentable.co.uk'
        @user_api_host_CI  = 'int-eu-svc'
        @user_api_host_PP = 'int-eu-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-eu-svc.otsql.opentable.com'
        @reservation_service_host_CI ='reservation-eu-ci.otenv.com'
        @reservation_service_host_PP ='reservation-eu-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-eu-ln.otenv.com'
        @reso_serv_port_PROD = "3046"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_service = "availability-eu.otenv.com"
        @availability_service_preprod = "availability-eu-pp-sf.otenv.com"
        @availability_service_prod = "availability-eu-prod-ln.otenv.com"
        @availability_service_ci = "availability-eu-ci-sf.otenv.com"
        @availability_domain = 'couk'
        $RESERVATION["restparam"] ="COUK"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id = '114'
        @webserver_site_port= '2091'
        @quality_center_test_set = 'CO.UK'
        @locale = 'en-GB'
        @www_otrestaurant_selector = "www.otrestaurant.com"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id ="5289"
        @region_lat ="51.5159400"
        @region_long = "-0.0910610"
        @soap_url ="http://www.opentable.co.uk/webservices/V3.asmx"
        @yml_param = "COUK"
        @availServer_sitetype_id = '810'
        @availServer_site_port = '3031'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1008"
        @internal_services = 'int-eu-svc'
        @reservation_service = 'reservation.eu.services.opentable.com'
        @region = 'EU'
        @language_id = '70'
        @int_services = "eu.services.opentable.com"
        @ios_bundle_id = "com.opentable.iPhone.TopTable-beta"
        @prod_int_services = 'int-eu-svc.otsql.opentable.com'
        @domain_id = '70'
        @metro_time_zone = 'Europe/London'
        @erb_domain_selector = 'erb.toptable.co.uk'
        @resource_locator_domain = 'couk'
        @umami_domain_selector = "https://guestcenter.opentable.co.uk"
        @tms_prod_url = "transaction-messaging.eu.services.opentable.com"
        @restaurant_service_prod  = "restaurant-ln.otenv.com"

      when ".ca"
        @domain = 'CA'
        @primary_metro_id = '201'
        @primary_country_id = "CA"
        @charm_domain_selector="OpenTable.ca"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.jp"
        @charm_prod_address = "charm-asia.opentable.com.ot"
        @db_server_address ="webdb-asia-primary"
        @db_name = "webdb_asia"
        @logdb_server_address ="weblogdb-asia-primary"
        @logdb_name = "WebLogDB_Asia"
        @mobile = 'm.opentable.jp'
        @rest = 'www.opentable.ca'
        $RESERVATION["restparam"] ="CA"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id ='222'
        @webserver_site_port = '2060'
        @quality_center_test_set = 'CA'
        @locale = 'fr-FR'
        @www_otrestaurant_selector = "www.otrestaurant#{domain}"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1001"
        @region_lat ="35.6670860"
        @region_long = "139.7304560"
        @soap_url ="http://www.opentable.com/webservices/V3.asmx"
        @yml_param = "CA"
        @availServer_sitetype_id = '811'
        @availServer_site_port = '3032'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1007"
        @internal_services = 'int-ap-svc'
        @language_id = '82'
        @int_services = "na.services.opentable.com"
        @prod_int_services = 'int-na-svc.otsql.opentable.com'
        @domain_id = '8'
        @erb_domain_selector = 'erb.opentable.ca'
        @umami_domain_selector = "https://guestcenter.opentable.ca"
        @tms_prod_url = "transaction-messaging.eu.services.opentable.com"
        @availability_service = "availability-na.otenv.com"
        @availability_service_preprod = "availability-na-pp-sf.otenv.com"
        @availability_service_prod = "availability-na-prod-sc.otenv.com"
        @availability_service_ci = "availability-na-ci-sf.otenv.com"
        @user_api_host_CI = 'int-na-svc'
        @user_api_host_PP = 'int-na-svc.qasql.opentable.com'
        @user_api_host_PROD = 'user-na-sc.otenv.com'
        @reservation_service_host_CI ='reservation-na-ci.otenv.com'
        @reservation_service_host_PP ='reservation-na-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-na-sc.otenv.com'
        @reso_serv_port_PROD = "3045"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_domain = 'com'
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      when ".ie"
        @domain = 'IE'
        @primary_metro_id = '3299'
        @primary_country_id = "IE"
        @charm_domain_selector="OpenTable.ie"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.eu"
        @charm_prod_address = "charm-eu.opentable.com.ot"
        @db_server_address ="webdb-eu-primary"
        @db_name = "webdb_eu"
        @logdb_server_address ="weblogdb-eu-primary"
        @logdb_name = "WebLogDB_EU"
        @offeravailabilitydb_server_address ="otofferavailability-eu-primary"
        @offeravailabilitydb_name = "OTOfferAvailability_EU"
        @mobile = 'm.opentable.ie'
        @rest = 'www.opentable.ie'
        @user_api_host_CI  = 'int-eu-svc'
        @user_api_host_PP = 'int-eu-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-eu-svc.otsql.opentable.com'
        @reservation_service_host_CI ='reservation-eu-ci.otenv.com'
        @reservation_service_host_PP ='reservation-eu-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-eu-ln.otenv.com'
        @reso_serv_port_PROD = "3046"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_service = "availability-eu.otenv.com"
        @availability_service_preprod = "availability-eu-pp-sf.otenv.com"
        @availability_service_prod = "availability-eu-prod-ln.otenv.com"
        @availability_service_ci = "availability-eu-ci-sf.otenv.com"
        @availability_domain = 'ie'
        $RESERVATION["restparam"] ="ie"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id = '114'
        @webserver_site_port= '2091'
        @quality_center_test_set = 'ie'
        @locale = 'en-GB'
        @www_otrestaurant_selector = "www.otrestaurant.com"
        @db_otr_server_address = "otrestaurant-eu-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id ="5289"
        @region_lat ="53.3477870"
        @region_long = "-6.2582990"
        @soap_url ="http://www.opentable.ie/webservices/V3.asmx"
        @yml_param = "IE"
        @availServer_sitetype_id = '810'
        @availServer_site_port = '3031'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1008"
        @internal_services = 'int-eu-svc'
        @reservation_service = 'reservation.eu.services.opentable.com'
        @region = 'EU'
        @language_id = '70'
        @int_services = "eu.services.opentable.com"
        @ios_bundle_id = "com.opentable.iPhone.TopTable-beta"
        @prod_int_services = 'int-eu-svc.otsql.opentable.com'
        @domain_id = '11'
        @metro_time_zone = 'Europe/Dublin'
        @erb_domain_selector = 'erb.toptable.ie'
        @resource_locator_domain = 'ie'
        @umami_domain_selector = "https://guestcenter.opentable.ie"
        @tms_prod_url = "transaction-messaging.eu.services.opentable.com"
        @restaurant_service_prod  = "restaurant-ln.otenv.com"

      when ".com.au"
        @domain = 'COM.AU'
        @primary_metro_id = '255'
        @primary_country_id = "AU"
        @charm_domain_selector="OpenTable.jp"
        @www_domain_selector = "www.opentable#{domain}"
        @charm_address = "www.charm.jp"
        @charm_prod_address = "charm-asia.opentable.com.ot"
        @db_server_address ="webdb-asia-primary"
        @db_name = "webdb_asia"
        @logdb_server_address ="weblogdb-asia-primary"
        @logdb_name = "WebLogDB_Asia"
        @mobile = 'm.opentable.com.au'
        @rest = 'www.opentable.com.au'
        # @user_api_host = 'int-ap-svc'
        @user_api_host_CI  = 'int-ap-svc'
        @user_api_host_PP = 'int-ap-svc.qasql.opentable.com'
        @user_api_host_PROD = 'int-ap-svc.otsql.opentable.com'
        @reservation_service_host_CI ='reservation-ap-ci.otenv.com'
        @reservation_service_host_PP ='reservation-ap-pp.otenv.com'
        @reservation_service_host_PROD ='reservation-ap-sc.otenv.com'
        @reso_serv_port_PROD = "3047"
        @reso_serv_port_PP = "80"
        @reso_serv_port_CI = "80"
        @availability_service = "availability-ap.otenv.com"
        @availability_service_ci = "availability-ap-ci-sf.otenv.com"
        @availability_service_preprod = "availability-ap-pp-sf.otenv.com"
        @availability_service_prod = "availability-ap-prod-sc.otenv.com"
        @availability_domain = 'com.au'
        $RESERVATION["restparam"] ="COM.AU"
        $RESERVATION["isRestref"] = false
        @webserver_sitetype_id ='102'
        @webserver_site_port = '2060'
        @quality_center_test_set = 'JP'
        @locale = 'ja-JP'
        @www_otrestaurant_selector = "www.otrestaurant#{domain}"
        @db_otr_server_address = "otrestaurant-na-primary-qa"
        @db_otr_name = "otrestaurant"
        @region_id="1001"
        @region_lat ="33.8650000"
        @region_long = "151.2094000"
        @soap_url ="http://www.opentable.com.au/webservices/V3.asmx"
        @yml_param = "COM.AU"
        @availServer_sitetype_id = '811'
        @availServer_site_port = '3032'
        @prod_primary_metro_id = "1"
        @prod_region_id = "1007"
        @internal_services = 'int-ap-svc'
        @reservation_service = 'reservation.ap.services.opentable.com'
        @region = 'AP'
        @language_id = '60'
        @int_services = "ap.services.opentable.com"
        @prod_int_services = 'int-ap-svc.otsql.opentable.com'
        @domain_id = '71'
        @metro_time_zone = 'Australia/Sydney'
        @erb_domain_selector = 'erb.opentable.jp'
        @resource_locator_domain = 'com.au'
        @umami_domain_selector = "https://guestcenter.opentable.com.au"
        @tms_prod_url = "transaction-messaging.na.services.opentable.com"
        @restaurant_service_prod  = "restaurant-sc.otenv.com"

      else
        raise RuntimeException, 'invalid domain'
    end
    if ENV['TEST_SUITE'].to_s.downcase == 'umami'
      if ENV['TEST_UMAMI_CLIENT_SERVER'].nil?
        @umami_domain_selector = UMAMI_HOSTS[@locale]['Front_end']['Host']
      else
        @umami_domain_selector = ENV['TEST_UMAMI_CLIENT_SERVER']
      end
      @umami_api_hosts['umami_front_end_host'] = @umami_domain_selector
      #@umami_api_hosts['umami_front_end_port'] = UMAMI_HOSTS[@locale]['Front_end']['Port']
      @umami_api_hosts['umami_back_end_host'] = UMAMI_HOSTS[@locale]['Back_end']['Host']
      @umami_api_hosts['umami_back_end_port'] = UMAMI_HOSTS[@locale]['Back_end']['Port']
      #@umami_api_hosts['umami_front_end_protocol'] = UMAMI_HOSTS[@locale]['Front_end']['Protocol']
      @umami_api_hosts['umami_back_end_protocol'] = UMAMI_HOSTS[@locale]['Back_end']['Protocol']
      @umami_pdiff_dir = File.join($image_directory, 'pdiff_images', @locale)
      @umami_pdiff_baseline_image_dir = File.join($image_directory, 'pdiff_images/baseline', @locale)
    end
    set_service_endpoints
  end

  def set_service_endpoints
      test_env =  ENV['TEST_ENVIRONMENT']
      puts 'in service endpoint method'
      unless test_env.nil?
        case test_env.to_s.upcase
          when 'PROD'
            @availability_service = @availability_service_prod
            @restaurant_service = @restaurant_service_prod
            @user_api_host = @user_api_host_PROD
            @reservation_service_host = @reservation_service_host_PROD
            @reso_serv_port = @reso_serv_port_PROD
            puts 'setting service references to prod endpoints'
          when 'PREPROD'
            @availability_service = @availability_service_preprod
            @restaurant_service = @restaurant_service_preprod
            @user_api_host = @user_api_host_PP
            @reservation_service_host = @reservation_service_host_PP
            @reso_serv_port = @reso_serv_port_PP
            puts 'setting service references to preprod endpoints'
          when 'CI', 'SFQA'
            @availability_service = @availability_service_ci
            @restaurant_service = @restaurant_service_ci
            @user_api_host = @user_api_host_CI
            @reservation_service_host = @reservation_service_host_CI
            @reso_serv_port = @reso_serv_port_CI
            puts 'setting service references to CI endpoints'
        end
      end
  end

  def inspect
    @www_domain_selector
  end

  def include? (arg)
    @www_domain_selector.include?(arg)
  end

  def to_s
    inspect
  end

end