USE QCReporting
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DomainLanguageMap]'))
DROP TABLE [dbo].[DomainLanguageMap]
GO

CREATE TABLE dbo.DomainLanguageMap
(
	 SiteType			varchar(50)	not null
	,DomainLanguage		varchar(50)	not null
	,CountryLanguage	varchar(50)	not null
	,Tier				int			null
	,LabTestSetCucumber	varchar(50)	null
	,LabTestSetQTP		varchar(50)	null

	 CONSTRAINT UNQ_DomainLanguageMap_LabTestSetCucumber			UNIQUE (LabTestSetCucumber)
	,CONSTRAINT UNQ_DomainLanguageMap_SiteType_DomainLanguage_Tier	UNIQUE (SiteType, DomainLanguage, Tier)
	,CONSTRAINT UNQ_DomainLanguageMap_SiteType_CountryLanguage_Tier	UNIQUE (SiteType, CountryLanguage, Tier)
)
GO

-- CONSUMER - ASIA
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('Consumer',	'.jp/ja-jp',			'Japan (.jp)/ja-JP',		0,		'ASIA\Consumer\Consumer BAT Tier 0 JP',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/en-gb',			'Japan (.jp)/en-GB',		0,		'ASIA\Consumer\Consumer BAT Tier 0 JP.en-GB',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/ja-jp',			'Japan (.jp)/ja-JP',		1,		'ASIA\Consumer\Consumer BAT Tier 1 JP',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/en-gb',			'Japan (.jp)/en-GB',		1,		'ASIA\Consumer\Consumer BAT Tier 1 JP.en-GB',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/ja-jp',			'Japan (.jp)/ja-JP',		2,		'ASIA\Consumer\Consumer BAT Tier 2 JP',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/en-gb',			'Japan (.jp)/en-GB',		2,		'ASIA\Consumer\Consumer BAT Tier 2 JP.en-GB',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/ja-jp',			'Japan (.jp)/ja-JP',		3,		'ASIA\Consumer\Consumer BAT Tier 3 JP',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.jp/en-gb',			'Japan (.jp)/en-GB',		3,		'ASIA\Consumer\Consumer BAT Tier 3 JP.en-GB',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.jp/jp-jp',	'Japan (.jp)/ja-JP',		-99,	'No Tier-.jp/ja-jp',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.jp/en-gb',	'Japan (.jp)/en-GB',		-99,	'No Tier-.jp/en-gb',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.jp/ja-jp',		'Japan (.jp)/ja-JP',		-98,	'???.jp/ja-jp',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.jp/en-gb',		'Japan (.jp)/en-GB',		-98,	'???.jp/en-gb',									null)

-- CONSUMER - EUROPE
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		0,		'EU\Consumer\Consumer BAT Tier 0 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/de-de',			'Germany (.de)/de-DE',		0,		'EU\Consumer\Consumer BAT Tier 0 DE',			'EU-de\WebBatTier0-DE')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/en-gb',			'Germany (.de)/en-GB',		0,		'EU\Consumer\Consumer BAT Tier 0 DE.en-GB',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/fr-fr',			'France (.fr)/fr-FR',		0,		'EU\Consumer\Consumer BAT Tier 0 FR',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/en-gb',			'France (.fr)/en-GB',		0,		'EU\Consumer\Consumer BAT Tier 0 FR.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/es-es',			'Spain (.es)/es-ES',		0,		'EU\Consumer\Consumer BAT Tier 0 ES',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/en-gb',			'Spain (.es)/en-GB',		0,		'EU\Consumer\Consumer BAT Tier 0 ES.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		1,		'EU\Consumer\Consumer BAT Tier 1 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/de-de',			'Germany (.de)/de-DE',		1,		'EU\Consumer\Consumer BAT Tier 1 DE',			'EU-de\WebBatTierI-DE')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/en-gb',			'Germany (.de)/en-GB',		1,		'EU\Consumer\Consumer BAT Tier 1 DE.en-GB',		'EU-de\WebBatTierI-enGB')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/fr-fr',			'France (.fr)/fr-FR',		1,		'EU\Consumer\Consumer BAT Tier 1 FR',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/en-gb',			'France (.fr)/en-GB',		1,		'EU\Consumer\Consumer BAT Tier 1 FR.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/es-es',			'Spain (.es)/es-ES',		1,		'EU\Consumer\Consumer BAT Tier 1 ES',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/en-gb',			'Spain (.es)/en-GB',		1,		'EU\Consumer\Consumer BAT Tier 1 ES.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		2,		'EU\Consumer\Consumer BAT Tier 2 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/de-de',			'Germany (.de)/de-DE',		2,		'EU\Consumer\Consumer BAT Tier 2 DE',			'EU-de\WebBatTierII-DE')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/en-gb',			'Germany (.de)/en-GB',		2,		'EU\Consumer\Consumer BAT Tier 2 DE.en-GB',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/fr-fr',			'France (.fr)/fr-FR',		2,		'EU\Consumer\Consumer BAT Tier 2 FR',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/en-gb',			'France (.fr)/en-GB',		2,		'EU\Consumer\Consumer BAT Tier 2 FR.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/es-es',			'Spain (.es)/es-ES',		2,		'EU\Consumer\Consumer BAT Tier 2 ES',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/en-gb',			'Spain (.es)/en-GB',		2,		'EU\Consumer\Consumer BAT Tier 2 ES.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		3,		'EU\Consumer\Consumer BAT Tier 3 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/de-de',			'Germany (.de)/de-DE',		3,		'EU\Consumer\Consumer BAT Tier 3 DE',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.de/en-gb',			'Germany (.de)/en-GB',		3,		'EU\Consumer\Consumer BAT Tier 3 DE.en-GB',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.fr/fr-fr',			'France (.fr)/fr-FR',		3,		'EU\Consumer\Consumer BAT Tier 3 FR',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.es/es-es',			'Spain (.es)/es-ES',		3,		'EU\Consumer\Consumer BAT Tier 3 ES',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.co.uk/en-gb',	'UK (.co.uk)/en-GB',		-99,	'No Tier-.co.uk/en-gb',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.de/de-de',	'Germany (.de)/de-DE',		-99,	'No Tier-.de/de-de',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.de/en-gb',	'Germany (.de)/en-GB',		-99,	'No Tier-.de/en-gb',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.fr/fr-fr',	'France (.fr)/fr-FR',		-99,	'No Tier-.fr/fr-fr',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.fr/en-gb',	'France (.fr)/en-GB',		-99,	'No Tier-.fr/en-gb',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.es/es-es',	'Spain (.es)/es-ES',		-99,	'No Tier-.es/es-es',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.es/en-gb',	'Spain (.es)/en-GB',		-99,	'No Tier-.es/en-gb',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.co.uk/en-gb',		'UK (.co.uk)/en-GB',		-98,	'???.co.uk/en-gb',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.de/de-de',		'Germany (.de)/de-DE',		-98,	'???.de/de-de',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.de/en-gb',		'Germany (.de)/en-GB',		-98,	'???.de/en-gb',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.fr/fr-fr',		'France (.fr)/fr-FR',		-98,	'???.fr/fr-fr',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.fr/en-gb',		'France (.fr)/en-GB',		-98,	'???.fr/en-gb',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.es/es-es',		'Spain (.es)/es-ES',		-98,	'???.es/es-es',									null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.es/en-gb',		'Spain (.es)/en-GB',		-98,	'???.es/en-gb',									null)

--update DomainLanguageMap set LabTestSetCucumber = 'NA\Consumer\Consumer BAT Tier 0 COM' where LabTestSetCucumber = 'NA\Consumer\Consumer BAT Tier 0 US'

-- CONSUMER - NORTH AMERICA
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/fr-ca',		'Canada (.com)/fr-CA',		0,		'NA\Consumer\Consumer BAT Tier 0 FR-CA',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/es-mx',		'Mexico (.com.mx)/es-MX',	0,		'NA\Consumer\Consumer BAT Tier 0 MX',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/en-us',		'Mexico (.com.mx)/en-US',	0,		'NA\Consumer\Consumer BAT Tier 0 MX.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com/en-us',			'US (.com)/en-US',			0,		'NA\Consumer\Consumer BAT Tier 0 COM',			'US\WebBatTier0')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/en-us',		'Canada (.com)/en-US',		0,		'EU\Consumer\Consumer BAT Tier 0 CA',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/fr-ca',		'Canada (.com)/fr-CA',		1,		'NA\Consumer\Consumer BAT Tier 1 FR-CA',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/es-mx',		'Mexico (.com.mx)/es-MX',	1,		'NA\Consumer\Consumer BAT Tier 1 MX',			'US\WebBatTierI-MX')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/en-us',		'Mexico (.com.mx)/en-US',	1,		'NA\Consumer\Consumer BAT Tier 1 MX.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com/en-us',			'US (.com)/en-US',			1,		'NA\Consumer\Consumer BAT Tier 1 COM',			'US\WebBatTierI')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/fr-ca',		'Canada (.com)/fr-CA',		2,		'NA\Consumer\Consumer BAT Tier 2 FR-CA',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/en-us',		'Canada (.com)/en-US',		1,		'EU\Consumer\Consumer BAT Tier 1 CA',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/es-mx',		'Mexico (.com.mx)/es-MX',	2,		'NA\Consumer\Consumer BAT Tier 2 MX',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/en-us',		'Mexico (.com.mx)/en-US',	2,		'NA\Consumer\Consumer BAT Tier 2 MX.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com/en-us',			'US (.com)/en-US',			2,		'NA\Consumer\Consumer BAT Tier 2 COM',			'US\WebBatTierII')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/en-us',		'Canada (.com)/en-US',		2,		'EU\Consumer\Consumer BAT Tier 2 CA',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/es-mx',		'Mexico (.com.mx)/es-MX',	3,		'NA\Consumer\Consumer BAT Tier 3 MX',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com.mx/en-us',		'Mexico (.com.mx)/en-US',	3,		'NA\Consumer\Consumer BAT Tier 3 MX.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com/en-us',			'US (.com)/en-US',			3,		'NA\Consumer\Consumer BAT Tier 3 COM',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'.com(ca)/en-us',		'Canada (.com)/en-US',		3,		'EU\Consumer\Consumer BAT Tier 3 CA',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.com(ca)/fr-ca','Canada (.com)/fr-CA',		-99,	'No Tier-.com(ca)/fr-ca',						null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.com.mx/es-mx','Mexico (.com.mx)/es-MX',	-99,	'No Tier-.com.mx/es-mx',						null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.com.mx/en-us','Mexico (.com.mx)/en-US',	-99,	'No Tier-.com.mx/en-us',						null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'No Tier-.com/en-us',	'US (.com)/en-US',			-99,	'No Tier-.com/en-us',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.com(ca)/fr-ca',	'Canada (.com)/fr-CA',		-98,	'???.com(ca)/fr-ca',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.com.mx/es-mx',	'Mexico (.com.mx)/es-MX',	-98,	'???.com.mx/es-mx',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.com.mx/en-us',	'Mexico (.com.mx)/en-US',	-98,	'???.com.mx/en-us',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A-.com/en-us',		'US (.com)/en-US',			-98,	'???.com/en-us',								null)

-- CONSUMER - NO LONGER APPLICABLE
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'???-uk.com/en-us',		'UK (.com)/en-US',			0,		'EU\Consumer\Consumer BAT Tier 0 COM.UK.en-US',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'???-uk.com/en-us',		'UK (.com)/en-US',			1,		'EU\Consumer\Consumer BAT Tier 1 COM.UK.en-US',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'???-uk.com/en-us',		'UK (.com)/en-US',			2,		'EU\Consumer\Consumer BAT Tier 2 COM.UK.en-US',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'???-uk.com/en-us',		'UK (.com)/en-US',			3,		'EU\Consumer\Consumer BAT Tier 3 COM.UK.en-US',	null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'???-No Tier-uk.com/en-us','UK (.com)/en-US',		-99,	'No Tier-uk.com/en-us',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'???-N/A-uk.com/en-us',	'UK (.com)/en-US',			-98,	'???uk.com/en-us',								null)


-- CHARM - NORTH AMERICA
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/en-us',			'US (.com)/en-US',			0,		'NA\CHARM\CHARM BAT Tier 0 COM',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/es-mx',			'Mexico (.com.mx)/es-MX',	0,		'NA\CHARM\CHARM BAT Tier 0 MX',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/mx-en-us',			'Mexico (.com.mx)/en-US',	0,		'NA\CHARM\CHARM BAT Tier 0 MX-en-US',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/fr-ca',			'Canada (.com)/fr-CA',		0,		'NA\CHARM\CHARM BAT Tier 0 FR-CA',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/en-us',			'US (.com)/en-US',			1,		'NA\CHARM\CHARM BAT Tier 1 COM',				'US\CharmBatTierI')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/es-mx',			'Mexico (.com.mx)/es-MX',	1,		'NA\CHARM\CHARM BAT Tier 1 MX',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/mx-en-us',			'Mexico (.com.mx)/en-US',	1,		'NA\CHARM\CHARM BAT Tier 1 MX-en-US',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/fr-ca',			'Canada (.com)/fr-CA',		1,		'NA\CHARM\CHARM BAT Tier 1 FR-CA',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/en-us',			'US (.com)/en-US',			2,		'NA\CHARM\CHARM BAT Tier 2 COM',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/es-mx',			'Mexico (.com.mx)/es-MX',	2,		'NA\CHARM\CHARM BAT Tier 2 MX',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/mx-en-us',			'Mexico (.com.mx)/en-US',	2,		'NA\CHARM\CHARM BAT Tier 2 MX-en-US',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/fr-ca',			'Canada (.com)/fr-CA',		2,		'NA\CHARM\CHARM BAT Tier 2 FR-CA',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/en-us',			'US (.com)/en-US',			3,		'NA\CHARM\CHARM BAT Tier 3 COM',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/es-mx',			'Mexico (.com.mx)/es-MX',	3,		'NA\CHARM\CHARM BAT Tier 3 MX',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/mx-en-us',			'Mexico (.com.mx)/en-US',	3,		'NA\CHARM\CHARM BAT Tier 3 MX-en-US',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.na/fr-ca',			'Canada (.com)/fr-CA',		3,		'NA\CHARM\CHARM BAT Tier 3 FR-CA',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'No Tier-.na/en-us',	'US (.com)/en-US',			-99,	'No Tier-.na/en-us',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'No Tier-.na/es-mx',	'Mexico (.com.mx)/es-MX',	-99,	'No Tier-.na/es-mx',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'No Tier-.na/fr-ca',	'Canada (.com)/fr-CA',		-99,	'No Tier-.na/fr-ca',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'???-.na/en-us',		'US (.com)/en-US',			-98,	'???-.na/en-us',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'???-.na/es-mx',		'Mexico (.com.mx)/es-MX',	-98,	'???-.na/es-mx',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'???-.na/fr-ca',		'Canada (.com)/fr-CA',		-98,	'???-.na/fr-ca',								null)

-- CHARM - EUROPE
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-de',			'Germany (.de)/de-DE',		0,		'EU\CHARM\CHARM BAT Tier 0 DE',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/uk-en-gb',			'UK (.co.uk)/en-GB',		0,		'EU\CHARM\CHARM BAT Tier 0 CO.UK',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-en-gb',			'Germany (.de)/en-GB',		0,		'EU\CHARM\CHARM BAT Tier 0 DE.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/fr-fr',			'France (.fr)/fr-FR',		0,		'EU\CHARM\CHARM BAT Tier 0 FR',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-de',			'Germany (.de)/de-DE',		1,		'EU\CHARM\CHARM BAT Tier 1 DE',					'EU-de\CharmBatTierI-DE')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/uk-en-gb',			'UK (.co.uk)/en-GB',		1,		'EU\CHARM\CHARM BAT Tier 1 CO.UK',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-en-gb',			'Germany (.de)/en-GB',		1,		'EU\CHARM\CHARM BAT Tier 1 DE.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/fr-fr',			'France (.fr)/fr-FR',		1,		'EU\CHARM\CHARM BAT Tier 1 FR',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-de',			'Germany (.de)/de-DE',		2,		'EU\CHARM\CHARM BAT Tier 2 DE',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/uk-en-gb',			'UK (.co.uk)/en-GB',		2,		'EU\CHARM\CHARM BAT Tier 2 CO.UK',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-en-gb',			'Germany (.de)/en-GB',		2,		'EU\CHARM\CHARM BAT Tier 2 DE.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/fr-fr',			'France (.fr)/fr-FR',		2,		'EU\CHARM\CHARM BAT Tier 2 FR',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-de',			'Germany (.de)/de-DE',		3,		'EU\CHARM\CHARM BAT Tier 3 DE',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/uk-en-gb',			'UK (.co.uk)/en-GB',		3,		'EU\CHARM\CHARM BAT Tier 3 CO.UK',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/de-en-gb',			'Germany (.de)/en-GB',		3,		'EU\CHARM\CHARM BAT Tier 3 DE.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'.eu/fr-fr',			'France (.fr)/fr-FR',		3,		'EU\CHARM\CHARM BAT Tier 3 FR',					null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'No Tier-.eu/de-de',	'Germany (.de)/de-DE',		-99,	'No Tier-.eu/de-de',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'No Tier-.eu/uk-en-gb',	'UK (.co.uk)/en-GB',		-99,	'No Tier-.eu/uk-en-gb',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'No Tier-.eu/de-en-gb',	'Germany (.de)/en-GB',		-99,	'No Tier-.eu/de-en-gb',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'No Tier-.eu/fr-fr',	'France (.fr)/fr-FR',		-99,	'No Tier-.eu/fr-fr',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'???-.eu/de-de',		'Germany (.de)/de-DE',		-98,	'???-.eu/de-de',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'???-.eu/uk-en-gb',		'UK (.co.uk)/en-GB',		-98,	'???-.eu/uk-en-gb',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'???-.eu/de-en-gb',		'Germany (.de)/en-GB',		-98,	'???-.eu/de-en-gb',								null)

-- CHARM - ASIA
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/ja-jp',			'Japan (.jp)/ja-JP',		0,		'ASIA\CHARM\CHARM BAT Tier 0 JP',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/jp-en-gb',		'Japan (.jp)/en-GB',		0,		'ASIA\CHARM\CHARM BAT Tier 0 JP.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/ja-jp',			'Japan (.jp)/ja-JP',		1,		'ASIA\CHARM\CHARM BAT Tier 1 JP',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/jp-en-gb',		'Japan (.jp)/en-GB',		1,		'ASIA\CHARM\CHARM BAT Tier 1 JP.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/ja-jp',			'Japan (.jp)/ja-JP',		2,		'ASIA\CHARM\CHARM BAT Tier 2 JP',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/jp-en-gb',		'Japan (.jp)/en-GB',		2,		'ASIA\CHARM\CHARM BAT Tier 2 JP.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/ja-jp',			'Japan (.jp)/ja-JP',		3,		'ASIA\CHARM\CHARM BAT Tier 3 JP',				null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'.asia/jp-en-gb',		'Japan (.jp)/en-GB',		3,		'ASIA\CHARM\CHARM BAT Tier 3 JP.en-GB',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'No Tier-.asia/ja-jp',	'Japan (.jp)/ja-JP',		-99,	'No Tier-.asia/ja-jp',							null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'No Tier-.asia/jp-en-gb','Japan (.jp)/en-GB',		-99,	'No Tier-.asia/jp-en-gb',						null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'???-.asia/ja-jp',		'Japan (.jp)/ja-JP',		-98,	'???-.asia/ja-jp',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP  )
values							('CHARM',		'???-.asia/ja-en-gb',	'Japan (.jp)/en-GB',		-98,	'???-.asia/ja-en-gb',							null)

-- CHARM - NO LONGER APPLICABLE
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'???-.na/uk',			'UK (.com)/en-US',			0,		'NA\CHARM\CHARM BAT Tier 0 NA.UK.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'???-.na/uk',			'UK (.com)/en-US',			1,		'NA\CHARM\CHARM BAT Tier 1 NA.UK.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'???-.na/uk',			'UK (.com)/en-US',			2,		'NA\CHARM\CHARM BAT Tier 2 NA.UK.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'???-.na/uk',			'UK (.com)/en-US',			3,		'NA\CHARM\CHARM BAT Tier 3 NA.UK.en-US',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'No Tier-.na/uk',		'UK (.com)/en-US',			-99,	'No Tier-.na/uk',								null)

-- MOBILE
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.com/en-us',			'US (.com)/en-US',			0,		'NA\Mobile\Mobile Site BAT Tier 0 COM',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		0,		'EU\Mobile\Mobile Site BAT Tier 0 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.de/de-de',			'Germany (.de)/de-DE',		0,		'EU\Mobile\Mobile Site BAT Tier 0 DE',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.com/en-us',			'US (.com)/en-US',			1,		'NA\Mobile\Mobile Site BAT Tier 1 COM',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		1,		'EU\Mobile\Mobile Site BAT Tier 1 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.de/de-de',			'Germany (.de)/de-DE',		1,		'EU\Mobile\Mobile Site BAT Tier 1 DE',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.com/en-us',			'US (.com)/en-US',			2,		'NA\Mobile\Mobile Site BAT Tier 2 COM',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.co.uk/en-gb',			'UK (.co.uk)/en-GB',		2,		'EU\Mobile\Mobile Site BAT Tier 2 CO.UK',		null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'.de/de-de',			'Germany (.de)/de-DE',		2,		'EU\Mobile\Mobile Site BAT Tier 2 DE',			null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'N/A-.com/en-us',		'US (.com)/en-US',			-98,	'???m..com/en-us',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'N/A-.co.uk/en-gb',		'UK (.co.uk)/en-GB',		-98,	'???m..co.uk/en-gb',								null)
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'N/A-.de/de-de',		'Germany (.de)/de-DE',		-98,	'???m..de/de-de',								null)

-- EVERYTHING ELSE
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('Consumer',	'N/A',					'N/A',						-99,	'N/A-Consumer',									'N/A-Consumer')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('CHARM',		'N/A',					'N/A',						-99,	'N/A-CHARM',									'N/A-CHARM')
insert into DomainLanguageMap	(SiteType,		DomainLanguage,			CountryLanguage,			Tier,	LabTestSetCucumber,								LabTestSetQTP )
values							('MobileSite',	'N/A',					'N/A',						-99,	'N/A-MobileSite',								'N/A-MobileSite')

GO
